name: Preview Pages
descriptions: Action to deploy multiple Github Pages

branding:
  icon: 'copy'
  color: 'blue'

inputs:
  github-token:
    description: The Github App token or personal access token to access Github Pages publishing repository
    required: true
  pages-organization:
    description: Organization of the Github Pages publishing repository
    required: true
  pages-repository:
    description: Repository name of the Github Pages publishing repository
    required: true
  path:
    description: Path of the directory containing the static assets to deploy
    required: true
  comment:
    description: Whether to comment the preview page url to a pull request
    default: 'true'
    required: false

runs:
  using: composite
  steps:
    - name: Set short sha
      id: short-sha
      run: echo "sha=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT

    - name: Set upload directory
      id: upload-dir
      run: echo "dir=${{ github.event_name == 'pull_request' && format('pr-{0}/{1}', github.event.number, steps.short-sha.outputs.sha) || github.ref_name }}" >> $GITHUB_OUTPUT

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        path: preview-pages
        repository: ${{ inputs.pages-organization }}/${{ inputs.pages-repository }}
        token: ${{ inputs.github-token }}

    - name: Move assets and check for diff
      id: diff-check
      working-directory: preview-pages
      run: |
        mv ${{ github.workspace }}/${{ inputs.path }} .
        git add -N .
        git diff --quiet || echo "has-diff=true" >> $GITHUB_OUTPUT

    - name: Install lucky_commit
      if: ${{ steps.diff-check.outputs.has-diff }}
      uses: baptiste0928/cargo-install@v2
      with:
        crate: lucky_commit
        args: --no-default-features

    - name: Commit
      if: ${{ steps.diff-check.outputs.has-diff }}
      run: |
        git config --global user.name "rajyan"
        git config --global user.email "kitakita7617@gmail.com"
        git add .
        git commit -m "Added coverage for ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.short-sha.outputs.sha }}"
        lucky_commit ${{ steps.short-sha.outputs.sha }}
        git push

    - name: Comment preview link
      if: ${{ steps.diff-check.outputs.has-diff && inputs.comment && github.event_name == 'pull_request' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "[Deployed page ${{ steps.short-sha.outputs.sha }}](https://rajyan.github.io/coverage-report/${{ steps.upload-dir.outputs.dir }})"
          })
