
name: "Test Commit"

on:
  pull_request:
  push:

jobs:
  run:
    name: "Run"

    runs-on: "ubuntu-latest"
    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Create directory"
        run: mkdir ${{ github.event.after }}

      - name: "Run something"
        working-directory: ${{ github.event.after }}
        if-no-files-found: error
        run: "touch test.md"

      - uses: actions/upload-artifact@v3
        with:
          name: pages
          path: ${{ github.event.after }}/test.md

  commit:
    name: "Commit"

    needs: run
    runs-on: "ubuntu-latest"
    timeout-minutes: 10

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.RAJYAN_BOT_APP_ID }}
          private_key: ${{ secrets.RAJYAN_BOT_PRIVATE_KEY }}

      - name: "Checkout target repository"
        uses: actions/checkout@v3
        with:
          repository: rajyan/coverage-report
          token: ${{ steps.generate_token.outputs.token }}

      - name: "Download"
        uses: actions/download-artifact@v3
        with:
          name: pages

      - name: "Install lucky_commit"
        uses: baptiste0928/cargo-install@v2
        with:
          crate: lucky_commit
          args: --no-default-features

      - name: "Commit"
        shell: bash -ex {0}
        run: |
          git config --global user.name "rajyan"
          git config --global user.email "kitakita7617@gmail.com"
          git status
          git add -A
          git commit -m "Added coverage for ${{ github.event.after }}"
          lucky_commit $(echo ${{ github.event.after }} | cut -c 1-7)
          git push