
name: "Test Commit"

on:
  pull_request:
  push:

jobs:
  run:
    name: "Run"

    runs-on: "ubuntu-latest"
    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run something"
        run: "touch index.md && echo 'test' >> index.md"

      - uses: actions/upload-artifact@v3
        with:
          name: pages
          if-no-files-found: error
          path: index.md

  commit:
    name: "Commit"

    needs: run
    runs-on: "ubuntu-latest"
    timeout-minutes: 10

    steps:
      - name: Set short sha
        id: short-sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.RAJYAN_BOT_APP_ID }}
          private_key: ${{ secrets.RAJYAN_BOT_PRIVATE_KEY }}

      - name: "Checkout target repository"
        uses: actions/checkout@v3
        with:
          repository: rajyan/coverage-report
          token: ${{ steps.generate_token.outputs.token }}

      - name: "Download"
        uses: actions/download-artifact@v3
        with:
          name: pages
          path: ${{ github.ref }}/${{ steps.short-sha.outputs.sha }}

      - name: 'Check'
        id: diff-check
        run: |
          git add -N .
          git diff --quiet || echo "has-diff=true" >> $GITHUB_OUTPUT

      - name: "Install lucky_commit"
        if: ${{steps.diff-check.outputs.has-diff}}
        uses: baptiste0928/cargo-install@v2
        with:
          crate: lucky_commit
          args: --no-default-features

      - name: "Commit"
        if: ${{steps.diff-check.outputs.has-diff}}
        run: |
          chmod 755 {{ github.ref }}/${{ steps.short-sha.outputs.sha }}
          git config --global user.name "rajyan"
          git config --global user.email "kitakita7617@gmail.com"
          git add .
          git commit -m "Added coverage for ${{ steps.short-sha.outputs.sha }}"
          lucky_commit ${{ steps.short-sha.outputs.sha }}
          git push